/**
 * Données initiales des véhicules pour le marché automobile en RDC
 * Statuts officiels pris en charge : pending, approved, rejected, sold, inactive
 */

const INITIAL_VEHICLES = [
  {
    id: 1,
    dealership_id: 1,
    user_id: 2,
    marque: 'Toyota',
    modele: 'Land Cruiser 300',
    finition: 'GR-Sport V6 Twin-Turbo 4x4',
    annee: 2024,
    prix: 145000,
    ancien_prix: 155000,
    msrp: 155000,
    remise_instantanee: 10000,
    en_promo: 1,
    kilometrage: 4500,
    carburant: 'Essence',
    transmission: 'Automatique',
    categorie: 'SUV',
    etat: 'neuf',
    status: 'approved',
    puissance_ch: 415,
    puissance_fiscale: 32,
    couleur: 'Blanc Nacré',
    couleur_interieure: 'Cuir Noir et Rouge GR',
    moteur: '3.5L V6 Twin-Turbo V35A-FTS',
    motrice: '4x4 Permanent (E-KDSS)',
    portes: 5,
    places: 7,
    co2_gkm: 275,
    garantie_mois: 36,
    vin: 'JTMCY79J4P4098231',
    ville: 'Kinshasa',
    commune: 'Gombe',
    description: 'Toyota Land Cruiser 300 GR Sport 2024 neuf. Véhicule tropicalisé d\'origine officielle pour l\'Afrique centrale. Système E-KDSS hydraulique, différentiels blocables avant/arrière, écrans multimédia arrière, suspensions adaptatives tout-terrain.',
    equipements: [
      'Climatisation Quadri-zone tropicalisée',
      'Suspension adaptative E-KDSS',
      'Toit ouvrant électrique',
      'Caméras 360° Multi-Terrain Monitor',
      'Système audio JBL 14 haut-parleurs',
      'Double réservoir carburant 110L',
      'Réfrigérateur de console centrale CoolBox'
    ],
    en_vedette: 1,
    views_count: 342,
    favorites_count: 28,
    created_at: new Date('2025-02-15T10:00:00Z'),
    updated_at: new Date('2025-02-15T10:00:00Z')
  },
  {
    id: 2,
    dealership_id: 1,
    user_id: 2,
    marque: 'Toyota',
    modele: 'Land Cruiser Prado',
    finition: 'TX-L 2.8 D-4D 7 Places',
    annee: 2023,
    prix: 78000,
    ancien_prix: 82000,
    msrp: 82000,
    remise_instantanee: 4000,
    en_promo: 1,
    kilometrage: 22000,
    carburant: 'Diesel',
    transmission: 'Automatique',
    categorie: 'SUV',
    etat: 'occasion',
    status: 'approved',
    puissance_ch: 204,
    puissance_fiscale: 15,
    couleur: 'Gris Métallisé',
    couleur_interieure: 'Cuir Beige',
    moteur: '2.8L 4-Cylindres D-4D Turbo Diesel',
    motrice: '4x4',
    portes: 5,
    places: 7,
    co2_gkm: 215,
    garantie_mois: 12,
    vin: 'JTEBX3FJ5P5012499',
    ville: 'Kinshasa',
    commune: 'Limete',
    description: 'Toyota Prado TX-L 2023 diesel en état exceptionnel. Immatriculé à Kinshasa, entretien suivi exclusivement en concession agréée. Très économique et robuste pour les trajets urbains et provinciaux.',
    equipements: [
      'Climatisation automatique tri-zone',
      'Écran tactile 9 pouces avec Apple CarPlay',
      'Sièges avant ventilés et chauffants',
      'Marchepieds latéraux éclairés',
      'Caméra de recul haute définition'
    ],
    en_vedette: 1,
    views_count: 512,
    favorites_count: 43,
    created_at: new Date('2025-02-18T14:30:00Z'),
    updated_at: new Date('2025-02-18T14:30:00Z')
  },
  {
    id: 3,
    dealership_id: 1,
    user_id: 3,
    marque: 'Toyota',
    modele: 'Hilux',
    finition: 'Revo Double Cabine 4x4 2.8L D-4D',
    annee: 2024,
    prix: 52000,
    ancien_prix: null,
    msrp: 52000,
    remise_instantanee: 0,
    en_promo: 0,
    kilometrage: 1500,
    carburant: 'Diesel',
    transmission: 'Manuelle',
    categorie: 'Pick-up',
    etat: 'neuf',
    status: 'approved',
    puissance_ch: 204,
    puissance_fiscale: 14,
    couleur: 'Argent Métallique',
    couleur_interieure: 'Tissu Renforcé Noir',
    moteur: '2.8L D-4D Diesel Intercooler',
    motrice: '4x4 Débrayable avec Réducteur',
    portes: 4,
    places: 5,
    co2_gkm: 198,
    garantie_mois: 36,
    vin: 'MROBA3CD7P1049581',
    ville: 'Lubumbashi',
    commune: 'Lubumbashi Centre',
    description: 'Toyota Hilux Revo 2024 Double Cabine 4x4. Véhicule tout-terrain neuf parfait pour les opérations minières, industrielles ou personnelles. Châssis renforcé Heavy Duty.',
    equipements: [
      'Transmission 4x4 avec blocage de différentiel arrière',
      'Arceau de sécurité benne en inox',
      'Bac de benne plastique renforcé',
      'Climatisation manuelle tropicalisée grand froid',
      'Phares antibrouillard LED'
    ],
    en_vedette: 0,
    views_count: 289,
    favorites_count: 19,
    created_at: new Date('2025-02-20T09:15:00Z'),
    updated_at: new Date('2025-02-20T09:15:00Z')
  },
  {
    id: 4,
    dealership_id: 1,
    user_id: 2,
    marque: 'Mercedes-Benz',
    modele: 'Classe G',
    finition: 'G 63 AMG V8 Biturbo Speedshift',
    annee: 2024,
    prix: 260000,
    ancien_prix: 280000,
    msrp: 280000,
    remise_instantanee: 20000,
    en_promo: 1,
    kilometrage: 800,
    carburant: 'Essence',
    transmission: 'Automatique',
    categorie: 'SUV',
    etat: 'neuf',
    status: 'approved',
    puissance_ch: 585,
    puissance_fiscale: 52,
    couleur: 'Noir Obsidienne Métallisé',
    couleur_interieure: 'Cuir Nappa Designo Rouge & Noir',
    moteur: '4.0L V8 Biturbo AMG M177',
    motrice: 'Transmission intégrale 4MATIC',
    portes: 5,
    places: 5,
    co2_gkm: 330,
    garantie_mois: 24,
    vin: 'W1N4632761X394812',
    ville: 'Kinshasa',
    commune: 'Gombe',
    description: 'Mercedes-Benz G63 AMG 2024. Le monstre de luxe et de puissance par excellence. 3 différentiels blocables à 100%, échappement sport commutable sorties latérales, pack nuit AMG.',
    equipements: [
      'Système audio Burmester Surround 3D',
      'Échappement sport AMG sorties latérales chromées',
      'Jantes forgées AMG 22 pouces noir mat',
      'Toit ouvrant électrique vitré',
      'Éclairage d\'ambiance 64 couleurs'
    ],
    en_vedette: 1,
    views_count: 1140,
    favorites_count: 95,
    created_at: new Date('2025-02-22T16:00:00Z'),
    updated_at: new Date('2025-02-22T16:00:00Z')
  },
  {
    id: 5,
    dealership_id: 1,
    user_id: 2,
    marque: 'Mercedes-Benz',
    modele: 'Classe E',
    finition: 'E 63 AMG S 4MATIC+ V8 Biturbo',
    annee: 2024,
    prix: 120000,
    ancien_prix: 130000,
    msrp: 130000,
    remise_instantanee: 10000,
    en_promo: 1,
    kilometrage: 1200,
    carburant: 'Essence',
    transmission: 'Automatique',
    categorie: 'Berline',
    etat: 'neuf',
    status: 'approved',
    puissance_ch: 612,
    puissance_fiscale: 55,
    couleur: 'Gris Sélénite Magno Mat',
    couleur_interieure: 'Cuir Nappa Exclusif Noir / Surpiqûres Jaunes',
    moteur: '4.0L V8 BiTurbo EQ Boost',
    motrice: 'AWD (4MATIC+)',
    portes: 4,
    places: 5,
    co2_gkm: 268,
    garantie_mois: 36,
    vin: 'W1KZF8HB3LA984122',
    ville: 'Kinshasa',
    commune: 'Gombe',
    description: 'Mercedes-Benz E63 AMG 2024 AWD Neuf. Moteur V8 BiTurbo développant 612 chevaux. Transmission intégrale 4MATIC+ avec mode Drift, suspension pneumatique AMG Ride Control+.',
    equipements: [
      'Suspension pneumatique AMG Ride Control+',
      'Pack Carbone Extérieur AMG',
      'Affichage tête haute dynamique Head-Up Display',
      'Toit ouvrant panoramique en verre',
      'Sièges Performance AMG massants et ventilés'
    ],
    en_vedette: 1,
    views_count: 670,
    favorites_count: 51,
    created_at: new Date('2025-02-23T11:00:00Z'),
    updated_at: new Date('2025-02-23T11:00:00Z')
  },
  {
    id: 6,
    dealership_id: 1,
    user_id: 3,
    marque: 'Ford',
    modele: 'Ranger Raptor',
    finition: '3.0L V6 EcoBoost Twin-Turbo 4x4',
    annee: 2024,
    prix: 82000,
    ancien_prix: 86000,
    msrp: 86000,
    remise_instantanee: 4000,
    en_promo: 1,
    kilometrage: 3500,
    carburant: 'Essence',
    transmission: 'Automatique',
    categorie: 'Pick-up',
    etat: 'occasion',
    status: 'approved',
    puissance_ch: 392,
    puissance_fiscale: 28,
    couleur: 'Bleu Lightning Métallisé',
    couleur_interieure: 'Alcantara Noir et Cuir Ford Performance',
    moteur: '3.0L V6 Twin-Turbo EcoBoost',
    motrice: '4x4 Permanent avec mode Baja',
    portes: 4,
    places: 5,
    co2_gkm: 315,
    garantie_mois: 24,
    vin: '6FPXXMJ2P8A019482',
    ville: 'Kolwezi',
    commune: 'Dilala',
    description: 'Ford Ranger Raptor 2024 V6 392 ch essence. Amortisseurs FOX 2.5 Live Valve à dérivation interne, mode d\'échappement actif, suspension arrière à bras de guidage de Watt.',
    equipements: [
      'Amortisseurs de course FOX 2.5 Live Valve',
      'Système audio Bang & Olufsen 10 haut-parleurs',
      'Plaque de protection sous moteur en acier 2.3mm',
      'Caméra 360 degrés tout-terrain'
    ],
    en_vedette: 0,
    views_count: 420,
    favorites_count: 36,
    created_at: new Date('2025-02-25T13:00:00Z'),
    updated_at: new Date('2025-02-25T13:00:00Z')
  },
  {
    id: 7,
    dealership_id: 1,
    user_id: 2,
    marque: 'Lexus',
    modele: 'LX 600',
    finition: 'VIP Lounge 4 Places Prestige',
    annee: 2024,
    prix: 195000,
    ancien_prix: null,
    msrp: 195000,
    remise_instantanee: 0,
    en_promo: 0,
    kilometrage: 2000,
    carburant: 'Essence',
    transmission: 'Automatique',
    categorie: 'SUV',
    etat: 'neuf',
    status: 'approved',
    puissance_ch: 415,
    puissance_fiscale: 32,
    couleur: 'Noir Starlight',
    couleur_interieure: 'Cuir Semi-Aniline Brun Ocre',
    moteur: '3.5L V6 Twin-Turbo',
    motrice: '4x4 AWD',
    portes: 5,
    places: 4,
    co2_gkm: 290,
    garantie_mois: 36,
    vin: 'JTJHY07W9P4019283',
    ville: 'Kinshasa',
    commune: 'Gombe',
    description: 'Lexus LX 600 VIP Lounge 2024. Configuration 4 places grand luxe avec fauteuils arrière de première classe inclinables à 48°, repose-jambes électrique et écran tactile de commande.',
    equipements: [
      'Sièges arrière Ottoman grand confort avec massage',
      'Système audio Mark Levinson Reference 25 haut-parleurs',
      'Suspension pneumatique hydraulique réglable en hauteur (AHC)',
      'Écrans vidéo individuels 11.6 pouces à l\'arrière'
    ],
    en_vedette: 1,
    views_count: 890,
    favorites_count: 72,
    created_at: new Date('2025-02-26T08:00:00Z'),
    updated_at: new Date('2025-02-26T08:00:00Z')
  },
  {
    id: 8,
    dealership_id: 1,
    user_id: 3,
    marque: 'Hyundai',
    modele: 'Tucson',
    finition: '1.6 T-GDi SmartSense Prestige',
    annee: 2023,
    prix: 34500,
    ancien_prix: 37000,
    msrp: 37000,
    remise_instantanee: 2500,
    en_promo: 1,
    kilometrage: 18000,
    carburant: 'Essence',
    transmission: 'Automatique',
    categorie: 'SUV',
    etat: 'occasion',
    status: 'approved',
    puissance_ch: 150,
    puissance_fiscale: 9,
    couleur: 'Blanc Polaire',
    couleur_interieure: 'Cuir Noir',
    moteur: '1.6L T-GDi 4-Cylindres Turbo',
    motrice: 'Traction (FWD)',
    portes: 5,
    places: 5,
    co2_gkm: 155,
    garantie_mois: 12,
    vin: 'KMHJ381EPNU384910',
    ville: 'Kinshasa',
    commune: 'Ngaliema',
    description: 'Hyundai Tucson 2023 essence automatique. SUV compact très maniable et économique pour Kinshasa. Feux avant intégrés dans la calandre, cockpit 100% digital.',
    equipements: [
      'Cockpit numérique 10.25 pouces avec navigation',
      'Freinage automatique d\'urgence autonome',
      'Chargeur de smartphone par induction sans fil',
      'Capteurs de stationnement avant et arrière + caméra'
    ],
    en_vedette: 0,
    views_count: 310,
    favorites_count: 22,
    created_at: new Date('2025-02-27T10:00:00Z'),
    updated_at: new Date('2025-02-27T10:00:00Z')
  },
  {
    id: 9,
    dealership_id: 1,
    user_id: 2,
    marque: 'Toyota',
    modele: 'RAV4',
    finition: '2.5 Hybride AWD-i Limited',
    annee: 2023,
    prix: 39000,
    ancien_prix: null,
    msrp: 39000,
    remise_instantanee: 0,
    en_promo: 0,
    kilometrage: 14000,
    carburant: 'Hybride',
    transmission: 'Automatique',
    categorie: 'SUV',
    etat: 'occasion',
    status: 'approved',
    puissance_ch: 222,
    puissance_fiscale: 11,
    couleur: 'Gris Magnétique',
    couleur_interieure: 'Cuir Noir',
    moteur: '2.5L 4-Cylindres + Moteur Électrique Hybride',
    motrice: 'AWD-i Intégrale électrique',
    portes: 5,
    places: 5,
    co2_gkm: 128,
    garantie_mois: 12,
    vin: '2T3R1RFV8PC283918',
    ville: 'Kinshasa',
    commune: 'Bandalungwa',
    description: 'Toyota RAV4 Hybride 2023 AWD. Consommation record en ville (moins de 5.5L / 100 km). Fiabilité légendaire du système hybride auto-rechargeable Toyota.',
    equipements: [
      'Motorisation hybride auto-rechargeable sans prise',
      'Hayon de coffre électrique mains libres',
      'Pack sécurité Toyota Safety Sense 2.5',
      'Toit ouvrant panoramique'
    ],
    en_vedette: 0,
    views_count: 450,
    favorites_count: 38,
    created_at: new Date('2025-02-28T09:00:00Z'),
    updated_at: new Date('2025-02-28T09:00:00Z')
  },
  {
    id: 10,
    dealership_id: 1,
    user_id: 2,
    marque: 'Nissan',
    modele: 'Patrol',
    finition: 'Nismo 5.6L V8 4x4',
    annee: 2023,
    prix: 115000,
    ancien_prix: 125000,
    msrp: 125000,
    remise_instantanee: 10000,
    en_promo: 1,
    kilometrage: 11000,
    carburant: 'Essence',
    transmission: 'Automatique',
    categorie: 'SUV',
    etat: 'occasion',
    status: 'approved',
    puissance_ch: 428,
    puissance_fiscale: 42,
    couleur: 'Blanc Perle',
    couleur_interieure: 'Alcantara et Cuir Noir / Rouge Nismo',
    moteur: '5.6L V8 Atmosphérique VK56VD',
    motrice: '4x4 All-Mode',
    portes: 5,
    places: 7,
    co2_gkm: 340,
    garantie_mois: 12,
    vin: 'JN8AY2NY1P9038271',
    ville: 'Kinshasa',
    commune: 'Gombe',
    description: 'Nissan Patrol Nismo 2023. Version sportive préparée par Nismo, suspension Bilstein sport, kit carrosserie aérodynamique exclusif, sonorité V8 envoûtante.',
    equipements: [
      'Amortisseurs sport Bilstein réglés par Nismo',
      'Jantes forgées RAYS 22 pouces bicolores',
      'Double écran tactile console centrale',
      'Système audio Bose Premium 13 haut-parleurs'
    ],
    en_vedette: 0,
    views_count: 530,
    favorites_count: 47,
    created_at: new Date('2025-03-01T15:00:00Z'),
    updated_at: new Date('2025-03-01T15:00:00Z')
  },
  // --- VÉHICULE AVEC STATUT : pending (en attente de modération) ---
  {
    id: 11,
    dealership_id: 1,
    user_id: 3,
    marque: 'Suzuki',
    modele: 'Jimny',
    finition: '1.5 GLX AllGrip Pro 4x4',
    annee: 2024,
    prix: 27000,
    ancien_prix: null,
    msrp: 27000,
    remise_instantanee: 0,
    en_promo: 0,
    kilometrage: 500,
    carburant: 'Essence',
    transmission: 'Manuelle',
    categorie: 'SUV',
    etat: 'neuf',
    status: 'pending',
    puissance_ch: 102,
    puissance_fiscale: 7,
    couleur: 'Vert Jungle',
    couleur_interieure: 'Tissu Noir Robuste',
    moteur: '1.5L 4-Cylindres K15B',
    motrice: '4x4 AllGrip Pro avec Boîte Courte',
    portes: 3,
    places: 4,
    co2_gkm: 178,
    garantie_mois: 24,
    vin: 'JS3JB74V5P0029481',
    ville: 'Kinshasa',
    commune: 'Kintambo',
    description: 'Suzuki Jimny 2024 neuf en attente de validation des documents douaniers. Vrai franchisseur compact à essieu rigide et boîte de transfert courte.',
    equipements: [
      'Transmission 4x4 avec boîte de transfert courte',
      'Phares LED automatiques avec lave-phares',
      'Écran tactile 7 pouces avec connectivité smartphone'
    ],
    en_vedette: 0,
    views_count: 85,
    favorites_count: 6,
    created_at: new Date('2025-03-02T11:00:00Z'),
    updated_at: new Date('2025-03-02T11:00:00Z')
  },
  // --- VÉHICULE AVEC STATUT : pending (deuxième exemple) ---
  {
    id: 12,
    dealership_id: 1,
    user_id: 2,
    marque: 'BMW',
    modele: 'X7',
    finition: 'M60i xDrive 7 Places V8',
    annee: 2024,
    prix: 138000,
    ancien_prix: 145000,
    msrp: 145000,
    remise_instantanee: 7000,
    en_promo: 1,
    kilometrage: 3200,
    carburant: 'Essence',
    transmission: 'Automatique',
    categorie: 'SUV',
    etat: 'occasion',
    status: 'pending',
    puissance_ch: 530,
    puissance_fiscale: 45,
    couleur: 'Bleu Marina Bay',
    couleur_interieure: 'Cuir Merino BMW Individual Tartufo',
    moteur: '4.4L V8 M TwinPower Turbo 48V',
    motrice: 'xDrive 4 roues motrices',
    portes: 5,
    places: 7,
    co2_gkm: 280,
    garantie_mois: 24,
    vin: '5UXCW2C08P9283710',
    ville: 'Kinshasa',
    commune: 'Gombe',
    description: 'BMW X7 M60i V8 2024. Annonce récemment déposée par la concession, en attente de vérification par l\'administrateur avant publication officielle.',
    equipements: [
      'Toit panoramique Sky Lounge illuminé par LED',
      'Système audio Bowers & Wilkins Diamond Surround',
      'Suspension pneumatique 2 essieux adaptative'
    ],
    en_vedette: 0,
    views_count: 62,
    favorites_count: 4,
    created_at: new Date('2025-03-03T10:00:00Z'),
    updated_at: new Date('2025-03-03T10:00:00Z')
  },
  // --- VÉHICULE AVEC STATUT : sold (vendu) ---
  {
    id: 13,
    dealership_id: 1,
    user_id: 2,
    marque: 'Mitsubishi',
    modele: 'Pajero Sport',
    finition: '2.4 DI-D 4x4 Exceed',
    annee: 2022,
    prix: 44000,
    ancien_prix: null,
    msrp: 44000,
    remise_instantanee: 0,
    en_promo: 0,
    kilometrage: 38000,
    carburant: 'Diesel',
    transmission: 'Automatique',
    categorie: 'SUV',
    etat: 'occasion',
    status: 'sold',
    puissance_ch: 181,
    puissance_fiscale: 12,
    couleur: 'Gris Titane',
    couleur_interieure: 'Cuir Noir',
    moteur: '2.4L MIVEC Turbo Diesel',
    motrice: 'Super Select 4WD-II',
    portes: 5,
    places: 7,
    co2_gkm: 212,
    garantie_mois: 6,
    vin: 'MMBJRKS10NH019284',
    ville: 'Goma',
    commune: 'Goma Centre',
    description: 'Mitsubishi Pajero Sport 2022 vendu la semaine dernière. Véhicule conservé en vitrine d\'historique des transactions certifiées CONGOCAR.',
    equipements: [
      'Transmission Super Select 4WD-II avec blocage',
      'Climatisation automatique bi-zone',
      'Caméras panoramiques Multi-Around Monitor'
    ],
    en_vedette: 0,
    views_count: 780,
    favorites_count: 31,
    created_at: new Date('2025-01-20T12:00:00Z'),
    updated_at: new Date('2025-02-28T17:00:00Z')
  },
  // --- VÉHICULE AVEC STATUT : rejected (rejeté par l'administrateur) ---
  {
    id: 14,
    dealership_id: 1,
    user_id: 3,
    marque: 'Land Rover',
    modele: 'Range Rover Sport',
    finition: 'D350 Dynamic HSE 3.0L',
    annee: 2024,
    prix: 155000,
    ancien_prix: null,
    msrp: 155000,
    remise_instantanee: 0,
    en_promo: 0,
    kilometrage: 6000,
    carburant: 'Diesel',
    transmission: 'Automatique',
    categorie: 'SUV',
    etat: 'occasion',
    status: 'rejected',
    puissance_ch: 350,
    puissance_fiscale: 26,
    couleur: 'Noir Santorini',
    couleur_interieure: 'Cuir Windsor Carvi et Ébène',
    moteur: '3.0L 6-Cylindres en ligne Ingenium Diesel MHEV',
    motrice: 'AWD 4x4 Permanent',
    portes: 5,
    places: 5,
    co2_gkm: 220,
    garantie_mois: 12,
    vin: 'SALWR2V87PA029381',
    ville: 'Kinshasa',
    commune: 'Gombe',
    description: 'Range Rover Sport D350 2024. Annonce rejetée par la modération : certificat de dédouanement et conformité du numéro de châssis en cours de vérification avec la DGI.',
    equipements: [
      'Suspension pneumatique dynamique avec amortisseurs bilatéraux',
      'Système audio Meridian 3D Surround 800W',
      'Projecteurs Digital LED avec signature visuelle'
    ],
    en_vedette: 0,
    views_count: 45,
    favorites_count: 2,
    created_at: new Date('2025-03-01T08:00:00Z'),
    updated_at: new Date('2025-03-01T09:30:00Z')
  },
  // --- VÉHICULE AVEC STATUT : inactive (inactif / archivé par le vendeur) ---
  {
    id: 15,
    dealership_id: 1,
    user_id: 2,
    marque: 'Kia',
    modele: 'Sportage',
    finition: 'GT-Line 1.6 T-GDi',
    annee: 2021,
    prix: 24500,
    ancien_prix: 26000,
    msrp: 26000,
    remise_instantanee: 1500,
    en_promo: 0,
    kilometrage: 42000,
    carburant: 'Essence',
    transmission: 'Automatique',
    categorie: 'SUV',
    etat: 'occasion',
    status: 'inactive',
    puissance_ch: 177,
    puissance_fiscale: 11,
    couleur: 'Rouge Fusion',
    couleur_interieure: 'Cuir et Tissu GT-Line Noir',
    moteur: '1.6L T-GDi Turbo Essence',
    motrice: 'Traction',
    portes: 5,
    places: 5,
    co2_gkm: 175,
    garantie_mois: 6,
    vin: 'KNAPM815AM5829104',
    ville: 'Kinshasa',
    commune: 'Matete',
    description: 'Kia Sportage GT-Line 2021. Annonce temporairement désactivée par le concessionnaire en raison d\'une révision mécanique complète à l\'atelier.',
    equipements: [
      'Ligne sportive GT-Line avec double canule chromée',
      'Toit panoramique ouvrant',
      'Écran multimédia compatible Carplay et Android Auto'
    ],
    en_vedette: 0,
    views_count: 210,
    favorites_count: 14,
    created_at: new Date('2025-01-10T14:00:00Z'),
    updated_at: new Date('2025-02-14T11:00:00Z')
  }
];

const INITIAL_VEHICLE_IMAGES = [
  // 1: Land Cruiser 300
  { id: 1, vehicle_id: 1, image_url: 'https://images.unsplash.com/photo-1594502184342-2e12f877aa73?auto=format&fit=crop&q=80&w=1200', is_primary: 1, display_order: 0 },
  { id: 2, vehicle_id: 1, image_url: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=1200', is_primary: 0, display_order: 1 },
  // 2: Land Cruiser Prado
  { id: 3, vehicle_id: 2, image_url: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&q=80&w=1200', is_primary: 1, display_order: 0 },
  { id: 4, vehicle_id: 2, image_url: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&q=80&w=1200', is_primary: 0, display_order: 1 },
  // 3: Toyota Hilux
  { id: 5, vehicle_id: 3, image_url: 'https://images.unsplash.com/photo-1559416523-140ddc3d238c?auto=format&fit=crop&q=80&w=1200', is_primary: 1, display_order: 0 },
  { id: 6, vehicle_id: 3, image_url: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=1200', is_primary: 0, display_order: 1 },
  // 4: Mercedes G63 AMG
  { id: 7, vehicle_id: 4, image_url: 'https://images.unsplash.com/photo-1520050206274-a1ae44613e6d?auto=format&fit=crop&q=80&w=1200', is_primary: 1, display_order: 0 },
  { id: 8, vehicle_id: 4, image_url: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&q=80&w=1200', is_primary: 0, display_order: 1 },
  // 5: Mercedes E63 AMG
  { id: 9, vehicle_id: 5, image_url: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&q=80&w=1200', is_primary: 1, display_order: 0 },
  { id: 10, vehicle_id: 5, image_url: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&q=80&w=1200', is_primary: 0, display_order: 1 },
  // 6: Ford Ranger Raptor
  { id: 11, vehicle_id: 6, image_url: 'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&q=80&w=1200', is_primary: 1, display_order: 0 },
  // 7: Lexus LX 600
  { id: 12, vehicle_id: 7, image_url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&q=80&w=1200', is_primary: 1, display_order: 0 },
  // 8: Hyundai Tucson
  { id: 13, vehicle_id: 8, image_url: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&q=80&w=1200', is_primary: 1, display_order: 0 },
  // 9: Toyota RAV4
  { id: 14, vehicle_id: 9, image_url: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&q=80&w=1200', is_primary: 1, display_order: 0 },
  // 10: Nissan Patrol
  { id: 15, vehicle_id: 10, image_url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=1200', is_primary: 1, display_order: 0 },
  // 11: Suzuki Jimny
  { id: 16, vehicle_id: 11, image_url: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=1200', is_primary: 1, display_order: 0 },
  // 12: BMW X7
  { id: 17, vehicle_id: 12, image_url: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&q=80&w=1200', is_primary: 1, display_order: 0 },
  // 13: Mitsubishi Pajero Sport
  { id: 18, vehicle_id: 13, image_url: 'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&q=80&w=1200', is_primary: 1, display_order: 0 },
  // 14: Range Rover Sport
  { id: 19, vehicle_id: 14, image_url: 'https://images.unsplash.com/photo-1506015391300-4802dc74de2e?auto=format&fit=crop&q=80&w=1200', is_primary: 1, display_order: 0 },
  // 15: Kia Sportage
  { id: 20, vehicle_id: 15, image_url: 'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&q=80&w=1200', is_primary: 1, display_order: 0 }
];

const INITIAL_FAVORITES = [
  { id: 1, user_id: 5, vehicle_id: 1, created_at: new Date('2025-02-20T10:00:00Z') },
  { id: 2, user_id: 5, vehicle_id: 4, created_at: new Date('2025-02-21T11:00:00Z') },
  { id: 3, user_id: 1, vehicle_id: 1, created_at: new Date('2025-02-22T08:00:00Z') }
];

module.exports = {
  INITIAL_VEHICLES,
  INITIAL_VEHICLE_IMAGES,
  INITIAL_FAVORITES
};
